### ISSUE TITLE
Criar Instrumented Tests para a UI da applicação

### ISSUE THREAD

**Issue by vanimarcos** [doesangueorg/android#13]
Criar testes instrumentais de UI para aplicação usando a biblioteca Expresso.
O desenvolvedor não pode realizar a toda a hora testes de UI, porque são demorados e consomem muito tempo.

**Comment by JoseCage** [comment]
Boas @vanimarcos.. Como funciona realmente esses testes?? 
Invoco @PEDRO33 e @JetroMobilha para analisarmos a implementação de "**`Instrumented Tests`**"

**Comment by vanimarcos** [comment]
Vou criar um vídeo e enviar para ti para veres como funciona.

**Comment by JoseCage** [comment]
> Vou criar um vídeo e evitar para ti para veres como funciona.

Se conseguir explicar melhor por vídeo, fixe.. Mas um texto nunca é demais..

PS: Pode mandar o vídeo pelo slack..

**Comment by vanimarcos** [comment]
[right_instrum.zip](https://github.com/doesangueorg/android/files/1402837/right_instrum.zip)

**Comment by vanimarcos** [comment]
Esse vídeo contem um teste de ui Automático.

**Comment by JoseCage** [comment]
> Esse vídeo contem um teste de ui Automático.

Porquê zipado?? É Uma volta a mais, baixar o zip, descomprimir e só assim abrir o vídeo..

Era mais simples usar algum serviço de hospedagem de vídeo ou mesmo fazer upload do vídeo no slack..

**Comment by JoseCage** [comment]
Prosseguindo, sobre o conteúdo do vídeo. Obrigado pela partilha.

Assisti porém não entendi bem.. 

`ping` @PEDRO33 @guimar86

**Comment by vanimarcos** [comment]
Porque o github não suporta upload de vídeo mp4. Achei melhor então zipar o
vídeo.

**Comment by vanimarcos** [comment]
Todo o software de qualidade tem testes unitários adicionam valor ao
produto. E test de UI ou Instrumented test é importante.

**Comment by JoseCage** [comment]
> Porque o github não suporta upload de vídeo mp4. Achei melhor então zipar o
> vídeo.

Sei. Mas para o caso ainda há alternativas como vimeo entre outras. Mas como esse não é o ponto da discussão vamos deixar para trás..

> Todo o software de qualidade tem testes unitários adicionam valor ao produto. E test de UI ou Instrumented test é importante.

@vanimarcos Quando diz teste de **UI** refere-se a testar a app em dispositivos moveis reais?

Não entendi bem o conceito até aqui rsrs..

**Comment by JoseCage** [comment]
Tentei fazer uma configuração de testes unitários com o **`TravisCI`** mas por algum motivo que desconheço dá erro de permissão no Travis e o teste não passa..

**Comment by vanimarcos** [comment]
Amanhã terá cda? Se sim eu apareço aí para tentarmos ver o problema.

**Comment by JoseCage** [comment]
> Amanhã terá cda? Se sim eu apareço aí para tentarmos ver o problema.

Terá sim @vanimarcos.. :+1:

**Comment by PEDRO33** [comment]
Bom dia, só abri o meu email agora. O que há de novo?

Jose Cage

2017-10-20 12:14 GMT-07:00 José Cage <notifications@github.com>:

**Comment by JoseCage** [comment]
> Bom dia, só abri o meu email agora. O que há de novo?

@PEDRO33  tens de ver a `issue` para estar dentro do assunto..
